/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/O2JUYV2HAnd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { generateImage } from "@/app/actions";
import { useState } from "react";
import Image from "next/image";

export function Generator() {
  const [url, setUrl] = useState('');
  const action = async (formData: FormData) => {
    const imageData  = await generateImage(formData)
    setUrl(imageData.data[0].url) 
    
  }
  return (
    <main className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <form action={action} className="max-w-md w-full space-y-4 px-4">
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">AI Image Generator</h1>
          <p className="text-gray-600 dark:text-gray-400">
            Enter a text prompt and let our AI generate an image for you.
          </p>
        </div>
        <div className="flex space-x-2">
          <Input
            className="flex-1 px-4 py-2 rounded-md border border-gray-200  dark:bg-gray-800 dark:text-gray-100 dark:border-gray-800"
            placeholder="Enter a text prompt"
            name="prompt"
            type="text"
          />
          <Button
            className="px-4 py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-600"
            type="submit"
          >
            Generate
          </Button>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-md shadow-md overflow-hidden">
          <Image
            alt="Generated Image"
            className="w-full h-auto"
            height="512"
            src={url === '' ? `/placeholder.svg` : url}
            style={{
              aspectRatio: "1:1",
              objectFit: "cover",
            }}
            width="512"
          />
        </div>
      </form>
    </main>
  )
}
